파티 해체 api 구현 #49#53
f-lab-edu/ottsharing pull request #106
Opened 2022-04-06 07:06 UTC by sue4869

2022-04-06 09:37 UTC, deepredk commented on src/main/java/kr/flab/ottsharing/config/SecurityConfig.java
> +@RequiredArgsConstructor // Security 필터가 등록됨 = 스프링 시큐리티가 이미 활성화는 되어있지만, 설정은 해당 파일에서 할 것임
요런 주석은 없어도 될 것 같습니다

2022-04-06 09:38 UTC, deepredk commented on src/main/java/kr/flab/ottsharing/config/SecurityConfig.java
> +@RequiredArgsConstructor // Security 필터가 등록됨 = 스프링 시큐리티가 이미 활성화는 되어있지만, 설정은 해당 파일에서 할 것임
아ㅏ JWT쪽인가보네요?

2022-04-06 09:38 UTC, deepredk commented
JWT 코드랑 섞여서 GitHub만으론 후딱 보기 어렵네요ㅠ
9시에 다시 와서 VSCode로 확인해볼게요!

2022-04-06 10:02 UTC, sue4869 commented on src/main/java/kr/flab/ottsharing/config/SecurityConfig.java
> +@RequiredArgsConstructor // Security 필터가 등록됨 = 스프링 시큐리티가 이미 활성화는 되어있지만, 설정은 해당 파일에서 할 것임
네

2022-04-06 12:23 UTC, deepredk commented on src/main/java/kr/flab/ottsharing/service/PartyService.java
> +    }
if (user.isPresent()) {
   throw new WrongInfoException()
}

User presentUser = user.get();

if (!memberService.checkLeader(presentUser)) {
    throw new WrongInfoException();
}

~~

이런식으로 고치면 코드가 더 깔끔해질 것 같습니다!

2022-04-06 12:30 UTC, deepredk commented on src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
> +    public Party PartyOfLeader(){
1. 네이버 코딩컨벤션에 따르면 함수 이름은 소문자, 동사로 시작해야 합니다!

2. checkLeader를 먼저 실행한 다음에 이 함수를 실행해야만 정상적으로 실행되는 감춰진 의존성?이 조금 아쉬운 것 같습니다

2022-04-06 12:30 UTC, deepredk requested changes
코딩컨벤션 checkstyle 검사 돌렸을때 경고 뜨는 부분이 꽤 많이 나오는데
슬슬 checkstyle 설치하고 이 PR부터 checkstyle 경고 잡아내보시면 좋을 것 같슴다!

2022-04-06 12:35 UTC, deepredk commented on src/main/java/kr/flab/ottsharing/service/LeaderMemberService.java
> +public class LeaderMemberService {
리더가 아닌 파티원이 사용하는 join(파티 가입)이라는 메서드때문에 기존 PartyMember가 적절할 것 같습니다

2022-04-06 12:52 UTC, sue4869 commented on src/main/java/kr/flab/ottsharing/service/LeaderMemberService.java
> +public class LeaderMemberService {
Leader를 위한 Service와 그냥 일반 파티원과 서비스단을 분리하고 싶어서 변경했습니다.

2022-04-06 12:55 UTC, deepredk commented on src/main/java/kr/flab/ottsharing/service/LeaderMemberService.java
> +public class LeaderMemberService {
아~ 그런거군요 이해했습니다!
커밋메시지에 표현됐다면 좋았을 것 같아요!

2022-04-06 13:01 UTC, sue4869 commented on src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
> +    public Party PartyOfLeader(){
순서가 
1. 리더인지 확인한다. 
2. 해당 리더가 속한 파티에 대한 정보를 가져온다
인데요 이때 해당 메소드가 없으면 2번을 위해 객체를 한번 더 만들어야 합니다. 해당 메소드는 처음에 리더인지 확인할 때 만들어진 객체를 활용합니다. 객체를 많이 만들수록 메모리상 좋지 않고, 동일한 객체를 이용한다는 생각에 진홍님 글의 2번내용과 같이 만들었습니다.

2022-04-06 13:04 UTC, deepredk commented on src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
> +    public Party PartyOfLeader(){
요건 제가 멘토님께 한번 여쭤보겠습니다!

2022-04-06 13:09 UTC, sue4869 commented on src/main/java/kr/flab/ottsharing/service/LeaderMemberService.java
> +public class LeaderMemberService {
아항 다음에는 더 자세히 표현하겠습니당!

2022-04-06 13:09 UTC, sue4869 commented on src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
> +    public Party PartyOfLeader(){
네!

2022-04-06 13:10 UTC, sue4869 commented on src/main/java/kr/flab/ottsharing/service/PartyService.java
> +    }
수정했습니당

2022-04-13 13:29 UTC, sue4869 commented
@deepredk  checkStyle 적용했습니다

2022-04-13 13:46 UTC, merged